// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"myweb/app/user/internal/cache"
	"myweb/app/user/internal/conf"
	"myweb/app/user/internal/dao"
	"myweb/app/user/internal/logic"
	"myweb/app/user/pkg/log"
	"myweb/app/user/pkg/mail"
	"myweb/app/user/pkg/util"
)

// Injectors from wire.go:

func InitUserServer() (*UserServer, error) {
	config := conf.NewConfig()
	db := dao.NewData(config)
	logger := log.NewLogger()
	userDao := dao.NewUserDao(db, logger)
	cacheCache := cache.NewCache(config, logger)
	jwtUtil := util.NewJwtUtil(config)
	emailUtil := mail.NewEmailUtil(config)
	userLogic := logic.NewUserLogic(userDao, cacheCache, jwtUtil, emailUtil, logger, config)
	userServer := NewUserServer(userLogic, userDao, cacheCache, jwtUtil, emailUtil, logger, config)
	return userServer, nil
}
