// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"myweb/app/gateway/internal/handler"
	"myweb/app/gateway/pkg/log"
	"myweb/app/gateway/register"
)

// Injectors from wire.go:

func InitGateway() (*Handlers, error) {
	logger := log.NewLogger()
	userHandler := handler.NewUserHandler(logger)
	etcdRegister, err := register.NewEtcdRegister()
	if err != nil {
		return nil, err
	}
	handlers := NewGateway(userHandler, etcdRegister)
	return handlers, nil
}
