// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"myweb/app/gateway/internal/handler"
	"myweb/app/gateway/pkg/log"
	"myweb/app/gateway/rpc"
)

// Injectors from wire.go:

func InitGateway() (*Handlers, error) {
	logger := log.NewLogger()
	userConn := rpc.NewUserConn()
	userHandler := handler.NewUserHandler(logger, userConn)
	handlers := NewGateway(userHandler)
	return handlers, nil
}
