// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.2
// source: user_model.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginResp_Case int32

const (
	LoginResp_OK                             LoginResp_Case = 0
	LoginResp_PasswordWrong                  LoginResp_Case = 1
	LoginResp_UserNotExists                  LoginResp_Case = 2
	LoginResp_VerificationCodeInvalid        LoginResp_Case = 3
	LoginResp_GivenUserHasNoVerificationCode LoginResp_Case = 4
)

// Enum value maps for LoginResp_Case.
var (
	LoginResp_Case_name = map[int32]string{
		0: "OK",
		1: "PasswordWrong",
		2: "UserNotExists",
		3: "VerificationCodeInvalid",
		4: "GivenUserHasNoVerificationCode",
	}
	LoginResp_Case_value = map[string]int32{
		"OK":                             0,
		"PasswordWrong":                  1,
		"UserNotExists":                  2,
		"VerificationCodeInvalid":        3,
		"GivenUserHasNoVerificationCode": 4,
	}
)

func (x LoginResp_Case) Enum() *LoginResp_Case {
	p := new(LoginResp_Case)
	*p = x
	return p
}

func (x LoginResp_Case) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginResp_Case) Descriptor() protoreflect.EnumDescriptor {
	return file_user_model_proto_enumTypes[0].Descriptor()
}

func (LoginResp_Case) Type() protoreflect.EnumType {
	return &file_user_model_proto_enumTypes[0]
}

func (x LoginResp_Case) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginResp_Case.Descriptor instead.
func (LoginResp_Case) EnumDescriptor() ([]byte, []int) {
	return file_user_model_proto_rawDescGZIP(), []int{2, 0}
}

type RegisterResp_Case int32

const (
	RegisterResp_OK              RegisterResp_Case = 0
	RegisterResp_EmailRegistered RegisterResp_Case = 1
	RegisterResp_NameRegistered  RegisterResp_Case = 2
)

// Enum value maps for RegisterResp_Case.
var (
	RegisterResp_Case_name = map[int32]string{
		0: "OK",
		1: "EmailRegistered",
		2: "NameRegistered",
	}
	RegisterResp_Case_value = map[string]int32{
		"OK":              0,
		"EmailRegistered": 1,
		"NameRegistered":  2,
	}
)

func (x RegisterResp_Case) Enum() *RegisterResp_Case {
	p := new(RegisterResp_Case)
	*p = x
	return p
}

func (x RegisterResp_Case) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisterResp_Case) Descriptor() protoreflect.EnumDescriptor {
	return file_user_model_proto_enumTypes[1].Descriptor()
}

func (RegisterResp_Case) Type() protoreflect.EnumType {
	return &file_user_model_proto_enumTypes[1]
}

func (x RegisterResp_Case) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisterResp_Case.Descriptor instead.
func (RegisterResp_Case) EnumDescriptor() ([]byte, []int) {
	return file_user_model_proto_rawDescGZIP(), []int{4, 0}
}

type GetVerificationCodeResp_Case int32

const (
	GetVerificationCodeResp_OK            GetVerificationCodeResp_Case = 0
	GetVerificationCodeResp_UserNotExists GetVerificationCodeResp_Case = 1
)

// Enum value maps for GetVerificationCodeResp_Case.
var (
	GetVerificationCodeResp_Case_name = map[int32]string{
		0: "OK",
		1: "UserNotExists",
	}
	GetVerificationCodeResp_Case_value = map[string]int32{
		"OK":            0,
		"UserNotExists": 1,
	}
)

func (x GetVerificationCodeResp_Case) Enum() *GetVerificationCodeResp_Case {
	p := new(GetVerificationCodeResp_Case)
	*p = x
	return p
}

func (x GetVerificationCodeResp_Case) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetVerificationCodeResp_Case) Descriptor() protoreflect.EnumDescriptor {
	return file_user_model_proto_enumTypes[2].Descriptor()
}

func (GetVerificationCodeResp_Case) Type() protoreflect.EnumType {
	return &file_user_model_proto_enumTypes[2]
}

func (x GetVerificationCodeResp_Case) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetVerificationCodeResp_Case.Descriptor instead.
func (GetVerificationCodeResp_Case) EnumDescriptor() ([]byte, []int) {
	return file_user_model_proto_rawDescGZIP(), []int{8, 0}
}

type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email  string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Avatar string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_user_model_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type LoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to LoginBy:
	//
	//	*LoginReq_Name
	//	*LoginReq_Email
	LoginBy isLoginReq_LoginBy `protobuf_oneof:"login_by"`
	// Types that are assignable to CertifyBy:
	//
	//	*LoginReq_Password
	//	*LoginReq_VerificationCode
	CertifyBy isLoginReq_CertifyBy `protobuf_oneof:"certify_by"`
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_user_model_proto_rawDescGZIP(), []int{1}
}

func (m *LoginReq) GetLoginBy() isLoginReq_LoginBy {
	if m != nil {
		return m.LoginBy
	}
	return nil
}

func (x *LoginReq) GetName() string {
	if x, ok := x.GetLoginBy().(*LoginReq_Name); ok {
		return x.Name
	}
	return ""
}

func (x *LoginReq) GetEmail() string {
	if x, ok := x.GetLoginBy().(*LoginReq_Email); ok {
		return x.Email
	}
	return ""
}

func (m *LoginReq) GetCertifyBy() isLoginReq_CertifyBy {
	if m != nil {
		return m.CertifyBy
	}
	return nil
}

func (x *LoginReq) GetPassword() string {
	if x, ok := x.GetCertifyBy().(*LoginReq_Password); ok {
		return x.Password
	}
	return ""
}

func (x *LoginReq) GetVerificationCode() string {
	if x, ok := x.GetCertifyBy().(*LoginReq_VerificationCode); ok {
		return x.VerificationCode
	}
	return ""
}

type isLoginReq_LoginBy interface {
	isLoginReq_LoginBy()
}

type LoginReq_Name struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3,oneof"`
}

type LoginReq_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

func (*LoginReq_Name) isLoginReq_LoginBy() {}

func (*LoginReq_Email) isLoginReq_LoginBy() {}

type isLoginReq_CertifyBy interface {
	isLoginReq_CertifyBy()
}

type LoginReq_Password struct {
	Password string `protobuf:"bytes,3,opt,name=password,proto3,oneof"`
}

type LoginReq_VerificationCode struct {
	VerificationCode string `protobuf:"bytes,4,opt,name=verification_code,json=verificationCode,proto3,oneof"`
}

func (*LoginReq_Password) isLoginReq_CertifyBy() {}

func (*LoginReq_VerificationCode) isLoginReq_CertifyBy() {}

type LoginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User  *UserInfo      `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token string         `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Case  LoginResp_Case `protobuf:"varint,3,opt,name=case,proto3,enum=pb.LoginResp_Case" json:"case,omitempty"`
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_model_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_model_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_user_model_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResp) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResp) GetCase() LoginResp_Case {
	if x != nil {
		return x.Case
	}
	return LoginResp_OK
}

type RegisterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_model_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_model_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_user_model_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RegisterResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Case RegisterResp_Case `protobuf:"varint,1,opt,name=case,proto3,enum=pb.RegisterResp_Case" json:"case,omitempty"`
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_model_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_model_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_user_model_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterResp) GetCase() RegisterResp_Case {
	if x != nil {
		return x.Case
	}
	return RegisterResp_OK
}

type RegisterVerifyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
}

func (x *RegisterVerifyReq) Reset() {
	*x = RegisterVerifyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_model_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterVerifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterVerifyReq) ProtoMessage() {}

func (x *RegisterVerifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_model_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterVerifyReq.ProtoReflect.Descriptor instead.
func (*RegisterVerifyReq) Descriptor() ([]byte, []int) {
	return file_user_model_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterVerifyReq) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type RegisterVerifyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User  *UserInfo `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token string    `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *RegisterVerifyResp) Reset() {
	*x = RegisterVerifyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_model_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterVerifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterVerifyResp) ProtoMessage() {}

func (x *RegisterVerifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_model_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterVerifyResp.ProtoReflect.Descriptor instead.
func (*RegisterVerifyResp) Descriptor() ([]byte, []int) {
	return file_user_model_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterVerifyResp) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RegisterVerifyResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetVerificationCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to GetBy:
	//
	//	*GetVerificationCodeReq_Email
	//	*GetVerificationCodeReq_Name
	GetBy isGetVerificationCodeReq_GetBy `protobuf_oneof:"get_by"`
}

func (x *GetVerificationCodeReq) Reset() {
	*x = GetVerificationCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_model_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVerificationCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerificationCodeReq) ProtoMessage() {}

func (x *GetVerificationCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_model_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerificationCodeReq.ProtoReflect.Descriptor instead.
func (*GetVerificationCodeReq) Descriptor() ([]byte, []int) {
	return file_user_model_proto_rawDescGZIP(), []int{7}
}

func (m *GetVerificationCodeReq) GetGetBy() isGetVerificationCodeReq_GetBy {
	if m != nil {
		return m.GetBy
	}
	return nil
}

func (x *GetVerificationCodeReq) GetEmail() string {
	if x, ok := x.GetGetBy().(*GetVerificationCodeReq_Email); ok {
		return x.Email
	}
	return ""
}

func (x *GetVerificationCodeReq) GetName() string {
	if x, ok := x.GetGetBy().(*GetVerificationCodeReq_Name); ok {
		return x.Name
	}
	return ""
}

type isGetVerificationCodeReq_GetBy interface {
	isGetVerificationCodeReq_GetBy()
}

type GetVerificationCodeReq_Email struct {
	Email string `protobuf:"bytes,1,opt,name=email,proto3,oneof"`
}

type GetVerificationCodeReq_Name struct {
	Name string `protobuf:"bytes,2,opt,name=name,proto3,oneof"`
}

func (*GetVerificationCodeReq_Email) isGetVerificationCodeReq_GetBy() {}

func (*GetVerificationCodeReq_Name) isGetVerificationCodeReq_GetBy() {}

type GetVerificationCodeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Case GetVerificationCodeResp_Case `protobuf:"varint,1,opt,name=case,proto3,enum=pb.GetVerificationCodeResp_Case" json:"case,omitempty"`
}

func (x *GetVerificationCodeResp) Reset() {
	*x = GetVerificationCodeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_model_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVerificationCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerificationCodeResp) ProtoMessage() {}

func (x *GetVerificationCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_model_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerificationCodeResp.ProtoReflect.Descriptor instead.
func (*GetVerificationCodeResp) Descriptor() ([]byte, []int) {
	return file_user_model_proto_rawDescGZIP(), []int{8}
}

func (x *GetVerificationCodeResp) GetCase() GetVerificationCodeResp_Case {
	if x != nil {
		return x.Case
	}
	return GetVerificationCodeResp_OK
}

var File_user_model_proto protoreflect.FileDescriptor

var file_user_model_proto_rawDesc = []byte{
	0x0a, 0x10, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x4c, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x22, 0x9f, 0x01, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x12, 0x14, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x1c, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x01, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x2d, 0x0a,
	0x11, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x10, 0x76, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x0a, 0x0a, 0x08,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x62, 0x79, 0x42, 0x0c, 0x0a, 0x0a, 0x63, 0x65, 0x72, 0x74,
	0x69, 0x66, 0x79, 0x5f, 0x62, 0x79, 0x22, 0xe2, 0x01, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x26, 0x0a, 0x04,
	0x63, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x43, 0x61, 0x73, 0x65, 0x52, 0x04,
	0x63, 0x61, 0x73, 0x65, 0x22, 0x75, 0x0a, 0x04, 0x43, 0x61, 0x73, 0x65, 0x12, 0x06, 0x0a, 0x02,
	0x4f, 0x4b, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x57, 0x72, 0x6f, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x4e,
	0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x10, 0x02, 0x12, 0x1b, 0x0a, 0x17, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x49, 0x6e,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x03, 0x12, 0x22, 0x0a, 0x1e, 0x47, 0x69, 0x76, 0x65, 0x6e,
	0x55, 0x73, 0x65, 0x72, 0x48, 0x61, 0x73, 0x4e, 0x6f, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x10, 0x04, 0x22, 0x53, 0x0a, 0x0b, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x22, 0x72, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x29, 0x0a, 0x04, 0x63, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x2e, 0x43, 0x61, 0x73, 0x65, 0x52, 0x04, 0x63, 0x61, 0x73, 0x65, 0x22, 0x37, 0x0a, 0x04, 0x43,
	0x61, 0x73, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x10, 0x01,
	0x12, 0x12, 0x0a, 0x0e, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x65, 0x64, 0x10, 0x02, 0x22, 0x2b, 0x0a, 0x11, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73,
	0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49,
	0x64, 0x22, 0x4c, 0x0a, 0x12, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x50, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x14, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x67, 0x65, 0x74, 0x5f, 0x62,
	0x79, 0x22, 0x72, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x34, 0x0a, 0x04,
	0x63, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x43, 0x61, 0x73, 0x65, 0x52, 0x04, 0x63, 0x61,
	0x73, 0x65, 0x22, 0x21, 0x0a, 0x04, 0x43, 0x61, 0x73, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b,
	0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69,
	0x73, 0x74, 0x73, 0x10, 0x01, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_model_proto_rawDescOnce sync.Once
	file_user_model_proto_rawDescData = file_user_model_proto_rawDesc
)

func file_user_model_proto_rawDescGZIP() []byte {
	file_user_model_proto_rawDescOnce.Do(func() {
		file_user_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_model_proto_rawDescData)
	})
	return file_user_model_proto_rawDescData
}

var file_user_model_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_user_model_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_user_model_proto_goTypes = []interface{}{
	(LoginResp_Case)(0),               // 0: pb.LoginResp.Case
	(RegisterResp_Case)(0),            // 1: pb.RegisterResp.Case
	(GetVerificationCodeResp_Case)(0), // 2: pb.GetVerificationCodeResp.Case
	(*UserInfo)(nil),                  // 3: pb.UserInfo
	(*LoginReq)(nil),                  // 4: pb.LoginReq
	(*LoginResp)(nil),                 // 5: pb.LoginResp
	(*RegisterReq)(nil),               // 6: pb.RegisterReq
	(*RegisterResp)(nil),              // 7: pb.RegisterResp
	(*RegisterVerifyReq)(nil),         // 8: pb.RegisterVerifyReq
	(*RegisterVerifyResp)(nil),        // 9: pb.RegisterVerifyResp
	(*GetVerificationCodeReq)(nil),    // 10: pb.GetVerificationCodeReq
	(*GetVerificationCodeResp)(nil),   // 11: pb.GetVerificationCodeResp
}
var file_user_model_proto_depIdxs = []int32{
	3, // 0: pb.LoginResp.user:type_name -> pb.UserInfo
	0, // 1: pb.LoginResp.case:type_name -> pb.LoginResp.Case
	1, // 2: pb.RegisterResp.case:type_name -> pb.RegisterResp.Case
	3, // 3: pb.RegisterVerifyResp.user:type_name -> pb.UserInfo
	2, // 4: pb.GetVerificationCodeResp.case:type_name -> pb.GetVerificationCodeResp.Case
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_user_model_proto_init() }
func file_user_model_proto_init() {
	if File_user_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_model_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_model_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_model_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_model_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterVerifyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_model_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterVerifyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_model_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVerificationCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_model_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVerificationCodeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_user_model_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*LoginReq_Name)(nil),
		(*LoginReq_Email)(nil),
		(*LoginReq_Password)(nil),
		(*LoginReq_VerificationCode)(nil),
	}
	file_user_model_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*GetVerificationCodeReq_Email)(nil),
		(*GetVerificationCodeReq_Name)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_model_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_model_proto_goTypes,
		DependencyIndexes: file_user_model_proto_depIdxs,
		EnumInfos:         file_user_model_proto_enumTypes,
		MessageInfos:      file_user_model_proto_msgTypes,
	}.Build()
	File_user_model_proto = out.File
	file_user_model_proto_rawDesc = nil
	file_user_model_proto_goTypes = nil
	file_user_model_proto_depIdxs = nil
}
